version: 2
jobs:
  build:
    docker:
      - image: abcum/circle:0.1.0
    working_directory: /go/src/github.com/abcum/cirrius
    steps:
      - checkout
      - run:
          name: Clean
          command: make clean
      - run:
          name: Glide
          command: make glide
      - run:
          name: Patch
          command: make patch
      - run:
          name: Tests
          command: make tests
      - run:
          name: Build
          command: make build
      - setup_remote_docker
      - run:
          name: Deploy
          command: |
            docker build -t abcum/cirrius .
            docker push abcum/cirrius
