version: 2
jobs:
  build:
    docker:
      - image: abcum/circle-webkit:latest
    working_directory: /go/src/github.com/abcum/cirrius
    steps:
      - checkout
      - run:
          name: Auth
          command: gcauth
      - run:
          name: Clean
          command: make clean
      - run:
          name: Glide
          command: make glide
      - run:
          name: Patch
          command: make patch
      - run:
          name: Tests
          command: make tests
      - run:
          name: Build
          command: make build
      - setup_remote_docker
      - run:
          name: Deploy
          command: |
            docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
            gcloud docker -- build -t abcum/cirrius .
            gcloud docker -- tag abcum/cirrius:latest eu.gcr.io/abcum-ltd/cirrius:latest
            gcloud docker -- push eu.gcr.io/abcum-ltd/cirrius:latest
